site_name: runpumpkin
site_description: Run a Pumpkin Minecraft server with your plugin for local testing
site_url: http://xodiumsoftware.github.io/runpumpkin
repo_name: XodiumSoftware/runpumpkin
repo_url: https://github.com/XodiumSoftware/runpumpkin
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started: getting-started.md
