name: Xodium CI/CD - Lib

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    environment:
      name: "${{ github.ref_name }}"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6.0.2

      - id: setup_rust
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@d197c158264056996cfba74a9c2d93886346edc3
        with:
          toolchain: stable
          components: rustfmt, clippy

      - id: run_lint
        name: Run Lint
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
          cargo fmt --all -- --check
        shell: bash

  build:
    name: Build
    needs: [ lint ]
    runs-on: ubuntu-latest
    environment:
      name: "${{ github.ref_name }}"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6.0.2

      - id: cache_dependencies
        name: Cache dependencies
        uses: actions/cache@v5.0.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - id: setup_rust
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@d197c158264056996cfba74a9c2d93886346edc3
        with:
          toolchain: stable

      - id: build_artifact
        name: Build Artefact
        run: cargo build --release --timings
        shell: bash

  nightly_publish:
    name: Nightly Publish
    needs: [ build ]
    runs-on: ubuntu-latest
    environment:
      name: "${{ github.ref_name }}"
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6.0.2

      - id: setup_rust
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@d197c158264056996cfba74a9c2d93886346edc3
        with:
          toolchain: stable

      - id: set_nightly_version
        name: Set Nightly Version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          CURRENT=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          sed -i "s/^version = \"${CURRENT}\"/version = \"${CURRENT}-nightly.${SHORT_SHA}\"/" Cargo.toml
        shell: bash

      - id: nightly_publish
        name: Publish Nightly to crates.io
        run: cargo publish --allow-dirty
        shell: bash
        continue-on-error: true
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CARGO_REGISTRY_TOKEN }}"
